[tools]
go = "1.26.4"
node = "20"
pnpm = "9.15.9"

[tasks.build]
description = "编译成单二进制"
run = "cd ./frontend && pnpm install && pnpm run build && cd ../backend && go build -tags embed -o sub2api ./cmd/server"
