name: Backend CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  backend-quality:
    name: Backend Quality
    uses: ./.github/workflows/backend-quality.yml
  frontend-quality:
    name: Frontend Quality
    uses: ./.github/workflows/frontend-quality.yml
